feat: add consul example and fix some errors
hertz-contrib/registry pull request #33
Opened 2023-01-09 03:55 UTC by Claude-Zq

#### What type of PR is this?
feat

#### What this PR does / why we need it (English/Chinese):

en: Add a more detailed example and fix some errors
zh: 添加了更详细的示例，并修正了部分错误

#### Which issue(s) this PR fixes:
https://github.com/cloudwego/hertz/issues/485

2023-01-09 08:40 UTC, welkeyever commented on consul/consul_test.go
> +// TestNewConsulResolver tests the NewConsulRegister function with check option.
What is the purpose of changing this? Seems that the keyword has not been completely changed?

2023-01-09 12:51 UTC, Claude-Zq commented on consul/consul_test.go
> +// TestNewConsulResolver tests the NewConsulRegister function with check option.
The purpose of changing this is that this code is to test the NewConsulRegister function with check option, not NewConsulResolver function.

2023-01-09 12:51 UTC, Claude-Zq commented on consul/consul_test.go
> +// TestNewConsulResolver tests the NewConsulRegister function with check option.
Already modified the keyword completely.👌🏻

2023-01-09 15:51 UTC, li-jin-gou requested changes

2023-01-09 15:51 UTC, li-jin-gou commented on consul/utils.go
> +func GetLocalIPv4Address() (string, error) {
why no use https://github.com/cloudwego/hertz/blob/develop/pkg/common/utils/network.go#L28  instead of GetLocalIPv4Address

2023-01-09 15:51 UTC, li-jin-gou commented on consul/example/custom-config/client/main.go
> +func main() {
add some client method refer to https://github.com/hertz-contrib/registry/issues/30

2023-01-10 02:23 UTC, Claude-Zq commented on consul/utils.go
> +func GetLocalIPv4Address() (string, error) {
utils.LocalIP returns IPv6 address, which will case panic in unit tests [TestConsulRegister,TestConsulDiscovery,TestConsulDeregister], so i refer to [registry-consul](https://github.com/kitex-contrib/registry-consul/blob/main/utils.go) which uses IPv4 address and works well.
![image](https://user-images.githubusercontent.com/86907968/211447260-199f4ba0-b242-4281-8077-6673784929fe.png)

2023-01-10 02:24 UTC, Claude-Zq commented on consul/example/custom-config/client/main.go
> +func main() {
done,Add post method.

2023-01-10 02:56 UTC, li-jin-gou commented on consul/utils.go
> +func GetLocalIPv4Address() (string, error) {
What about ipv6 only scenarios?

2023-01-19 08:03 UTC, Claude-Zq commented on consul/utils.go
> +func GetLocalIPv4Address() (string, error) {
done

2023-02-05 08:46 UTC, li-jin-gou approved these changes

2023-02-05 08:46 UTC, li-jin-gou commented
LGTM

2023-02-05 09:19 UTC, L2ncE approved these changes

2023-02-05 12:24 UTC, justlorain approved these changes

2023-02-05 12:33 UTC, merged