feat: add retry feature for etcd
hertz-contrib/registry pull request #91
Opened 2023-09-28 16:26 UTC by Skyenought

#### What type of PR is this?
feat

#### What this PR does / why we need it (English/Chinese):
zh: 给 etcd 增加重试能力

#### Which issue(s) this PR fixes:

2023-09-29 14:32 UTC, chaoranz758 commented on etcd/registry.go
> +	if err := e.keepalive(meta); err != nil {
这个地方为啥要改呢

2023-09-29 14:45 UTC, chaoranz758 commented on etcd/registry.go
> +		cancel()
这个地方还是用 defer cancel() 好一点吧，万一 Get 里有 panic 可能就执行不到这了

2023-09-29 14:49 UTC, chaoranz758 commented on etcd/registry.go
> +		cancel()
再加下相关的单测吧

2023-09-29 14:52 UTC, chaoranz758 commented on etcd/readme.md
> +```
这块没必要加吧，告知用户如何传入配置项及配置项默认值即可

2023-09-29 14:52 UTC, Skyenought commented on etcd/registry.go
> +	if err := e.keepalive(meta); err != nil {
因为指针可能会 data race，ai 告警了

2023-09-29 14:54 UTC, chaoranz758 commented on etcd/registry.go
> +	if err := e.keepalive(meta); err != nil {
> 因为指针可能会 data race，ai 告警了

ok

2023-09-29 14:57 UTC, Skyenought commented on etcd/registry.go
> +		cancel()
有更好的解决方法吗，我看 for 里面可能内存泄露

2023-09-29 15:05 UTC, Skyenought commented on etcd/registry.go
> +		cancel()
会被 warning

2023-09-29 15:05 UTC, Skyenought commented on etcd/readme.md
> +```
也可以

2023-09-29 15:08 UTC, chaoranz758 commented on etcd/registry.go
> +		cancel()
查了一下，可以把 Get 包在一个协程里，这样应该可以解决 https://www.jianshu.com/p/5652c0903f5e

2023-10-03 13:59 UTC, chaoranz758 commented on etcd/registry.go
> +			defer cancel()
defer cancel() 放在 Get 前面

2023-10-03 14:08 UTC, li-jin-gou requested changes
+单测

2023-10-04 09:44 UTC, chaoranz758 approved these changes

2023-10-05 10:51 UTC, li-jin-gou commented on etcd/etcd_test.go
> +func (e *etcdRegistry) keepRegisterForTest(key, val string, retryConfig *retryCfg) (reqTime int, observeDelayCorrect, retryDelayCorrect bool) {
这个单测逻辑的用途是??

2023-10-05 10:58 UTC, li-jin-gou requested changes

2023-10-05 10:58 UTC, li-jin-gou commented on etcd/etcd_test.go
> +func TestEtcdRegistryKeepRegister(t *testing.T) {
完善单测

2023-10-05 16:59 UTC, li-jin-gou approved these changes

2023-10-05 16:59 UTC, merged