imgrate nacos-sdk-go to v2
hertz-contrib/registry pull request #99
Opened 2024-01-07 15:51 UTC by PolarishT

#### What type of PR is this?

feat: A new feature support nacos-sdk-go v2

#### What this PR does / why we need it (English/Chinese):
current hertz discovery do not support nacos-sdk-go-v2

#### Which issue(s) this PR fixes:
#96

2024-01-08 03:13 UTC, li-jin-gou commented
可以参考 https://github.com/kitex-contrib/registry-nacos/blob/main/v2/README.md ，简略一点就可以，因为 API 是一样的。

2024-01-08 03:38 UTC, li-jin-gou requested changes
单测没过，需要修改

2024-01-09 02:31 UTC, Skyenought commented on nacos/v2/go.mod
> +module github.com/hertz-contrib/registry/nacosv2
module github.com/hertz-contrib/registry/nacos/v2

2024-01-09 02:31 UTC, Skyenought commented on nacos/v2/exmaple/custom_config/client/main.go
> +// Copyright 2023 CloudWeGo Authors.
typo exmaple -> example

2024-01-09 15:00 UTC, closed without merging